version: '3'
services:
    ubuntu:
        build:
            context: .
            dockerfile: ./build/Dockerfile
            args: 
                User: ${user}
                JUPYTER_PASSWD: ${jupyter_passwd}
                JUPYTER_PORT: ${jupyter_port}
                JUPYTER_WORK_DIR: /home/${user}/${jupyter_work_dir}

        image: tf1-py3
        runtime: nvidia
        user: ${user}
        working_dir: /home/${user}
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            # - "/usr/local/cuda:/usr/local/cuda"
            - "./sandbox:/home/${user}/sandbox"
        ports: 
            - "8888:${jupyter_port}"
        command: /bin/bash
        tty: true
        